export const USER_LOGIN_INITIATED = "USER_LOGIN_INITIATED";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const USER_REGISTRATION_INITIATED = "USER_REGISTRATION_INITIATED";
export const USER_REGISTRATION_FAILED = "USER_REGISTRATION_FAILED";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";

export const NEW_TRANSACTION_INITIATED = "NEW_TRANSACTION_INITIATED";
export const NEW_TRANSACTION_FAILED = "NEW_TRANSACTION_FAILED";
export const NEW_TRANSACTION_SUCCESS = "NEW_TRANSACTION_SUCCESS";

export const LOAD_USER_INITIATED = "LOAD_USER_INITIATED";
export const LOAD_USER_FAILED = "LOAD_USER_FAILED";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";

export const SET_HEADERS_AUTHTOKEN = "SET_HEADERS_AUTHTOKEN";

export const LOAD_USERSTO_INITIATED = "LOAD_USERSTO_INITIATED";
export const LOAD_USERSTO_FAILED = "LOAD_USERSTO_FAILED";
export const LOAD_USERSTO_SUCCESS = "LOAD_USERSTO_SUCCESS";

export const LOGOUT_USER = "LOGOUT_USER";